Sprint-10. Add friends likes
EugeneChenBy/java-filmorate pull request #4
Opened 2023-05-16 19:50 UTC by EugeneChenBy

Добавление в приложение слоев хранения данных и их обработки. Добавление логики хранения друзей и лайков

2023-05-17 19:56 UTC, Donald522 requested changes

2023-05-17 19:56 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes = new HashSet<>();
Тут советую хранить просто кол-во лайков в виде integer

2023-05-17 19:56 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.error(e.getMessage());
Зачем ловить и перебрасывать то же исключение? Логировать надо в ExceptionHandler

2023-05-17 19:56 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilmsList().stream()
Эту логику лучше перенести на уровень storage
Когда будет база, то доставать из базы в приложение все данные и на уровне приложения взять только 10 из них будет неверно

2023-05-17 19:56 UTC, Donald522 commented
Привет!
В целом все здорово, написал пару предложений что можно улучшить.

2023-05-17 22:27 UTC, EugeneChenBy commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes = new HashSet<>();
В подсказках к ТЗ было про Set. Ну и он напрашивается исходя из задачи поставить/снять лайк. Если здесь хранить только количество, то придется хранить сами лайки в пользователях. Я посчитал текущий вариант более экономным

2023-05-17 22:34 UTC, EugeneChenBy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.error(e.getMessage());
Абсолютно согласен, убрал.
Торопился, осталось от предыдущего решения

2023-05-17 23:01 UTC, EugeneChenBy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilmsList().stream()
Согласен. Перенёс.

2023-05-18 20:02 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes = new HashSet<>();
Хорошо.
Но когда будет база, то вариант с хранением кол-ва лайков будет лучше.

2023-05-18 20:04 UTC, Donald522 approved these changes
Привет!

По поводу кол-ва лайков понял тебя, пусть так будет. 
Когда будем делать базу то советую попробовать сделать как я предложил - там получится лучше в плане эффективности построения рейтинга.

2023-05-22 17:41 UTC, merged